// Design system Salvaê — componentes reutilizáveis (fonte: contexto-design.md).
export { Text } from "./Text";
export type { AppTextProps } from "./Text";
export { Screen } from "./Screen";
export { SafeAreaInsetBottom } from "./SafeAreaInsetBottom";
export { Card } from "./Card";
export { PrimaryButton, SecondaryButton } from "./Button";
export { Money } from "./Money";
export { PriceTag } from "./PriceTag";
export { CountdownChip } from "./CountdownChip";
export { SafeBadge } from "./SafeBadge";
export { SafetySeal } from "./SafetySeal";
export type { SafetySealData } from "./SafetySeal";
export { InfoRow } from "./InfoRow";
export { FilterChip } from "./FilterChip";
export { SectionHeader } from "./SectionHeader";
export { IconTile } from "./IconTile";
export { ScreenHeader } from "./ScreenHeader";
export { AppHeader } from "./AppHeader";
export { StatusPill } from "./StatusPill";
export type { StatusTone } from "./StatusPill";
export { QuantityStepper } from "./QuantityStepper";
export { EmptyState } from "./EmptyState";
export { Divider } from "./Divider";
export { Avatar } from "./Avatar";
export { SearchField } from "./SearchField";
export { SelectableRow } from "./SelectableRow";
export { ListRow } from "./ListRow";
export { Tag } from "./Tag";
export { AddressCard } from "./AddressCard";
export type { AddressCardModel } from "./AddressCard";
export { TextField } from "./TextField";
export { OfferCard } from "./OfferCard";
export type { OfferCardModel } from "./OfferCard";
