import type { Establishment } from "../model/establishment";

/**
 * Dados mockados para navegação offline (etapa atual).
 * Formato = contrato previsto para o backend C# .NET.
 */
export const ESTABLISHMENTS_MOCK: Establishment[] = [
  {
    id: "est-padaria-central",
    name: "Padaria Central",
    category: "BAKERY",
    logoUrl: "https://picsum.photos/seed/padaria-central-logo/120",
    coverUrl: "https://picsum.photos/seed/padaria-central-cover/800/400",
    addressLine: "Rua das Flores, 123 - Pinheiros",
    distanceMeters: 800,
    rating: 4.7,
    safetyRating: 4.9,
    isVerifiedPartner: true,
  },
  {
    id: "est-mercado-preco-bom",
    name: "Mercado Preço Bom",
    category: "GROCERY",
    logoUrl: "https://picsum.photos/seed/preco-bom-logo/120",
    coverUrl: "https://picsum.photos/seed/preco-bom-cover/800/400",
    addressLine: "Av. Rebouças, 940 - Jardim Paulista",
    distanceMeters: 1500,
    rating: 4.4,
    safetyRating: 4.6,
    isVerifiedPartner: true,
  },
  {
    id: "est-hortifruti-verde",
    name: "Hortifruti Verde",
    category: "PRODUCE",
    logoUrl: "https://picsum.photos/seed/hortifruti-verde-logo/120",
    coverUrl: "https://picsum.photos/seed/hortifruti-verde-cover/800/400",
    addressLine: "Rua Cardeal Arcoverde, 210 - Pinheiros",
    distanceMeters: 650,
    rating: 4.6,
    safetyRating: 4.7,
    isVerifiedPartner: true,
  },
  {
    id: "est-mercado-da-vila",
    name: "Mercado da Vila",
    category: "GROCERY",
    logoUrl: "https://picsum.photos/seed/mercado-da-vila-logo/120",
    coverUrl: "https://picsum.photos/seed/mercado-da-vila-cover/800/400",
    addressLine: "Rua Harmonia, 77 - Vila Madalena",
    distanceMeters: 1200,
    rating: 4.5,
    safetyRating: 4.5,
    isVerifiedPartner: true,
  },
  {
    id: "est-cafe-e-cia",
    name: "Café & Cia",
    category: "RESTAURANT",
    logoUrl: "https://picsum.photos/seed/cafe-e-cia-logo/120",
    coverUrl: "https://picsum.photos/seed/cafe-e-cia-cover/800/400",
    addressLine: "Rua Fradique Coutinho, 1500 - Pinheiros",
    distanceMeters: 500,
    rating: 4.8,
    safetyRating: 4.8,
    isVerifiedPartner: true,
  },
  {
    id: "est-mercado-verde",
    name: "Mercado Verde",
    category: "GROCERY",
    logoUrl: "https://picsum.photos/seed/mercado-verde-logo/120",
    coverUrl: "https://picsum.photos/seed/mercado-verde-cover/800/400",
    addressLine: "Av. Paulista, 2100 - Bela Vista",
    distanceMeters: 2300,
    rating: 4.3,
    safetyRating: 4.4,
    isVerifiedPartner: true,
  },
];
