import type { Salvado } from "../model/salvado";

const now = Date.now();
const minutes = (n: number) => new Date(now + n * 60_000).toISOString();
const hours = (n: number) => new Date(now + n * 60 * 60_000).toISOString();

/**
 * Dados mockados para navegação offline (etapa atual).
 * Formato = contrato previsto para o backend C# .NET (dinheiro em centavos,
 * datas ISO 8601, enums estáveis).
 */
export const SALVADOS_MOCK: Salvado[] = [
  {
    id: "slv-cesta-paes-artesanais",
    establishmentId: "est-padaria-central",
    name: "Cesta de Pães Artesanais",
    description:
      "Contém 4 pães franceses e 2 integrais produzidos hoje. Uma excelente oportunidade para resgatar produtos frescos no fim do expediente. Ideal para o lanche ou acompanhamento de refeições.",
    imageUrl: "https://picsum.photos/seed/cesta-paes-artesanais/600/400",
    category: "BAKERY",
    kind: "REGULAR",
    originalPriceInCents: 1800,
    priceInCents: 800,
    weightGrams: 900,
    quantityAvailable: 5,
    publishedAt: minutes(-90),
    offerExpiresAt: minutes(45),
    pickupWindow: {
      date: new Date(now).toISOString().slice(0, 10),
      startTime: "18:00",
      endTime: "19:30",
      label: "Retirar hoje, 18:00 - 19:30",
    },
    safetySeal: {
      availability: "Disponível até hoje, 22h",
      conservation: "Mantido em temperatura ambiente",
      responsible: "Informado pela Padaria Central",
      consumeWithinHours: null,
    },
    isSafe: true,
  },
  {
    id: "slv-kit-laticinios",
    establishmentId: "est-mercado-preco-bom",
    name: "Kit Laticínios",
    description:
      "Seleção de iogurtes, queijo minas e requeijão próximos da data de validade, todos dentro do prazo de consumo seguro.",
    imageUrl: "https://picsum.photos/seed/kit-laticinios/600/400",
    category: "DAIRY",
    kind: "REGULAR",
    originalPriceInCents: 4590,
    priceInCents: 1590,
    weightGrams: 1600,
    quantityAvailable: 3,
    publishedAt: hours(-2),
    offerExpiresAt: hours(2),
    pickupWindow: {
      date: new Date(now).toISOString().slice(0, 10),
      startTime: "17:00",
      endTime: "20:00",
      label: "Retirar hoje, 17:00 - 20:00",
    },
    safetySeal: {
      availability: "Disponível até amanhã, 12h",
      conservation: "Mantido sob refrigeração (até 5°C)",
      responsible: "Informado pelo Mercado Preço Bom",
      consumeWithinHours: null,
    },
    isSafe: true,
  },
  {
    id: "slv-mix-frutas",
    establishmentId: "est-hortifruti-verde",
    name: "Mix de Frutas",
    description:
      "Bananas, maçãs e mamão maduros, perfeitos para consumo imediato, vitaminas e bolos. Sem risco de segurança, apenas aparência madura.",
    imageUrl: "https://picsum.photos/seed/mix-frutas/600/400",
    category: "PRODUCE",
    kind: "REGULAR",
    originalPriceInCents: 3500,
    priceInCents: 1250,
    weightGrams: 2500,
    quantityAvailable: 8,
    publishedAt: hours(-5),
    offerExpiresAt: hours(6),
    pickupWindow: {
      date: new Date(now).toISOString().slice(0, 10),
      startTime: "09:00",
      endTime: "21:00",
      label: "Retirar hoje, até 21:00",
    },
    safetySeal: {
      availability: "Disponível até hoje",
      conservation: "Mantido em temperatura ambiente",
      responsible: "Informado pelo Hortifruti Verde",
      consumeWithinHours: null,
    },
    isSafe: true,
  },
  {
    id: "slv-sacola-mista-hortifruti",
    establishmentId: "est-mercado-da-vila",
    name: "Sacola Mista - Hortifruti",
    description:
      "Caixa Surpresa com legumes e verduras da estação selecionados pela equipe do mercado. Você não sabe o conteúdo exato — e ajuda a evitar o desperdício.",
    imageUrl: "https://picsum.photos/seed/sacola-mista-hortifruti/600/400",
    category: "PRODUCE",
    kind: "SURPRISE_BAG",
    originalPriceInCents: 3500,
    priceInCents: 1500,
    weightGrams: 3000,
    quantityAvailable: 4,
    publishedAt: hours(-1),
    offerExpiresAt: hours(2),
    pickupWindow: {
      date: new Date(now).toISOString().slice(0, 10),
      startTime: "16:00",
      endTime: "19:00",
      label: "Retirar hoje, 16:00 - 19:00",
    },
    safetySeal: {
      availability: "Disponível até amanhã",
      conservation: "Mantido em temperatura ambiente",
      responsible: "Informado pelo Mercado da Vila",
      consumeWithinHours: null,
    },
    isSafe: true,
  },
  {
    id: "slv-kit-doces-do-dia",
    establishmentId: "est-cafe-e-cia",
    name: "Kit Doces do Dia",
    description:
      "Bolos de pote, brownies e cookies preparados hoje pela confeitaria. Frescos, apenas excedente de produção do dia.",
    imageUrl: "https://picsum.photos/seed/kit-doces-do-dia/600/400",
    category: "SWEETS",
    kind: "REGULAR",
    originalPriceInCents: 4200,
    priceInCents: 1250,
    weightGrams: 1100,
    quantityAvailable: 2,
    publishedAt: minutes(-40),
    offerExpiresAt: minutes(15),
    pickupWindow: {
      date: new Date(now).toISOString().slice(0, 10),
      startTime: "18:30",
      endTime: "19:30",
      label: "Retirar hoje, 18:30 - 19:30",
    },
    safetySeal: {
      availability: "Disponível até hoje, 20h",
      conservation: "Mantido sob refrigeração",
      responsible: "Informado pelo Café & Cia",
      consumeWithinHours: 24,
    },
    isSafe: true,
  },
  {
    id: "slv-marmita-executiva",
    establishmentId: "est-cafe-e-cia",
    name: "Marmita Executiva do Dia",
    description:
      "Excedente do almoço executivo: arroz, feijão, proteína e salada. Preparado hoje, mantido quente até a retirada.",
    imageUrl: "https://picsum.photos/seed/marmita-executiva/600/400",
    category: "HOT_MEAL",
    kind: "REGULAR",
    originalPriceInCents: 2900,
    priceInCents: 1200,
    weightGrams: 650,
    quantityAvailable: 6,
    publishedAt: minutes(-30),
    offerExpiresAt: minutes(80),
    pickupWindow: {
      date: new Date(now).toISOString().slice(0, 10),
      startTime: "14:00",
      endTime: "15:00",
      label: "Retirar hoje, 14:00 - 15:00",
    },
    safetySeal: {
      availability: "Preparada hoje às 11h30",
      conservation: "Mantida aquecida (acima de 60°C)",
      responsible: "Informado pelo Café & Cia",
      consumeWithinHours: 3,
    },
    isSafe: true,
  },
  {
    id: "slv-kit-hortifruti",
    establishmentId: "est-mercado-verde",
    name: "Kit Hortifruti",
    description: "Seleção de legumes e folhas para a semana, com pequenas avarias estéticas.",
    imageUrl: "https://picsum.photos/seed/kit-hortifruti/600/400",
    category: "PRODUCE",
    kind: "REGULAR",
    originalPriceInCents: 3000,
    priceInCents: 1400,
    weightGrams: 2200,
    quantityAvailable: 0,
    publishedAt: hours(-30),
    offerExpiresAt: hours(-6),
    pickupWindow: {
      date: new Date(now - 24 * 3600_000).toISOString().slice(0, 10),
      startTime: "18:00",
      endTime: "20:00",
      label: "Retirada encerrada",
    },
    safetySeal: {
      availability: "Oferta encerrada",
      conservation: "Mantido em temperatura ambiente",
      responsible: "Informado pelo Mercado Verde",
      consumeWithinHours: null,
    },
    isSafe: true,
  },
];
